---
title: "ASHG Scholars Initiative Application 2023"
format: html
---


CV/Resume 
Please include academic achievements, research accomplishments, community engagement and leadership activities. (Please use NIH Biosketch-Fellowship Template here.)

https://grants.nih.gov/grants/forms/biosketch.htm


No file chosen
Personal Statement 
Please explain how you will benefit from the HGSI program, how the program will affect your short and long-term career goals, and comment on your interests and commitment to fostering workforce diversity in human genetics.

Fostering workforce diversity can include but is not limited to:

Mentoring underrepresented groups interested in research.
Participating in career discussions attended by those underrepresented in research with your organization or at professional meetings.
Participating in science education at K-12 schools that have a diverse student population, e.g. science fair judge or attendance at a Career Day.
Participating in outreach activities in underserved communities.
Word count: 0 / 500

